name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4
  
     - name: Setup node
       uses: actions/setup-node@v4
  
     - name: Install dependencies
       run: npm install
  
     - name: Build static file
       run: npm run build

     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ vars.AWS_REGION}}

     - name: List s3 files
       run: aws s3 ls s3://${{ vars.AWS_BUCKET_NAME}}
         
     - name: Deploy static site to S3 bucket
       run: aws s3 rm s3://${{ vars.AWS_BUCKET_NAME}} --recursive

     - name: List s3 files 2
       run: aws s3 ls s3://${{ vars.AWS_BUCKET_NAME}}
         
     - name: Deploy static site to S3 bucket
       run: aws s3 sync ./build s3://${{ vars.AWS_BUCKET_NAME}}

     - name: List s3 files 3
       run: aws s3 ls s3://${{ vars.AWS_BUCKET_NAME}}
